//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingDBEntities : DbContext
    {
        public ParkingDBEntities()
            : base("name=ParkingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gate> Gates { get; set; }
        public virtual DbSet<ParkedVehicle> ParkedVehicles { get; set; }
        public virtual DbSet<ParkingRate> ParkingRates { get; set; }
        public virtual DbSet<ParkingSpace> ParkingSpaces { get; set; }
    }
}
