//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingRate
    {
        public int RateId { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> PenaltyRate { get; set; }
    }
}
