//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpace()
        {
            this.ParkedVehicles = new HashSet<ParkedVehicle>();
        }
    
        public int SpaceId { get; set; }
        public Nullable<int> GateId { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
    
        public virtual Gate Gate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkedVehicle> ParkedVehicles { get; set; }
    }
}
