//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkedVehicle
    {
        public int ParkingId { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> SpaceId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
    }
}
